env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

builds:
  - id: macos
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
    dir: ./cmd/gon/

archives:
  - id: macos-zip
    format: zip
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}

checksum:
  disable: true

signs:
  - signature: "${artifact}_macos.zip"
    ids:
      - macos-zip
    cmd: gon
    args:
      - --log-level=debug
      - .gon.hcl
    artifacts: all

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - 'README'

release:
  ids:
    - none
  extra_files:
    - glob: ./dist/gon_macos.zip

brews:
  - tap:
      owner: conductorone
      name: homebrew-gon
    description: "Sign, notarize, and package macOS CLI applications written in any language."
